######################################################################
# Automatically generated by qmake (1.04a) Fri Jan 19 15:05:50 2007
######################################################################

TEMPLATE = app

CONFIG -= moc

INCLUDEPATH += . ../globe

LIBS += -L../globe -lmyerr

TARGET = id

# Input
SOURCES += id.c
