######################################################################
# Automatically generated by qmake (1.04a) Fri Jan 19 15:05:50 2007
######################################################################

TEMPLATE = app

CONFIG -= moc

INCLUDEPATH += . ../globe

LIBS += -L../globe -lmyerr

TARGET = 1.3

# Input
SOURCES += 1.3.c
