######################################################################
# Automatically generated by qmake (1.04a) Fri Jan 19 15:05:50 2007
######################################################################

TEMPLATE = app

CONFIG -= qt

INCLUDEPATH += ../globe

LIBS += -L../globe -lmyerr

TARGET = myls

# Input
SOURCES += myls.c
