######################################################################
# Automatically generated by qmake (1.04a) Fri Jan 19 15:10:23 2007
######################################################################

TEMPLATE = lib

CONFIG += staticlib debug warn_on

INCLUDEPATH += .

TARGET = myerr

# Input
HEADERS += ourhdr.h
SOURCES += myerror.c
